### ISSUE TITLE
conda create should be condo env create

### ISSUE THREAD

**Issue by hanlinm2** [ysig/diff-mining#2]
According to [conda documentation](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) and my experiment,

it should be 
`conda env create -f environment.yaml` 
instead of 
`conda create -f environment.yaml` in the Readme

**Comment by ysig** [comment]
Fixed. Thanks for pointing it out 😊
